{"ray": {"sid": "911189b0c1fc4cfab8350a75a44437a3", "uid": null, "qid": "03cc351b1c4d45818d01676a5648cc0e", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [03cc351b1c4d45818d01676a5648cc0e]\nTraceback (most recent call last):\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/openfabric_pysdk/app/worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 68, in execute\n    context_model, qa_model = model_loading()\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 60, in model_loading\n    context_model = ContextModel()\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 26, in __init__\n    self.question_encoder = AutoModelForTextEncoding.from_pretrained('bert-base-uncased').to(self.device)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1723, in __setattr__\n    raise AttributeError(\nAttributeError: cannot assign module before Module.__init__() call\n", "created_at": "2023-12-14T01:10:35.064587"}], "status": "FAILED", "created_at": "2023-12-14T01:10:23.990896", "updated_at": "2023-12-14T01:10:35.091162", "finished": true}, "in": {"text": ["hello, openfabric"]}, "out": {}}