{"ray": {"sid": "a6658af9624041cc96087e8a0f39e765", "uid": null, "qid": "714131fc6f274a468c087f7619ba1687", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [714131fc6f274a468c087f7619ba1687]\nTraceback (most recent call last):\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/openfabric_pysdk/app/worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 84, in execute\n    answer = qa_model(text, context)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 54, in forward\n    outputs = self.model.generate(**inputs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/generation/utils.py\", line 1593, in generate\n    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/generation/utils.py\", line 742, in _prepare_encoder_decoder_kwargs_for_generation\n    model_kwargs[\"encoder_outputs\"]: ModelOutput = encoder(**encoder_kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/accelerate/hooks.py\", line 165, in new_forward\n    output = module._old_forward(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 1110, in forward\n    layer_outputs = layer_module(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/accelerate/hooks.py\", line 165, in new_forward\n    output = module._old_forward(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 694, in forward\n    self_attention_outputs = self.layer[0](\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/accelerate/hooks.py\", line 165, in new_forward\n    output = module._old_forward(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 601, in forward\n    attention_output = self.SelfAttention(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/accelerate/hooks.py\", line 165, in new_forward\n    output = module._old_forward(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 543, in forward\n    position_bias = self.compute_bias(real_seq_length, key_length, device=scores.device)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 443, in compute_bias\n    relative_position_bucket = self._relative_position_bucket(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 413, in _relative_position_bucket\n    relative_buckets += (relative_position > 0).to(torch.long) * num_buckets\ntorch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 426.00 MiB. GPU 0 has a total capacty of 3.81 GiB of which 274.00 MiB is free. Including non-PyTorch memory, this process has 3.54 GiB memory in use. Of the allocated memory 3.43 GiB is allocated by PyTorch, and 49.70 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n", "created_at": "2023-12-14T03:22:18.172323"}], "status": "FAILED", "created_at": "2023-12-14T03:22:01.898876", "updated_at": "2023-12-14T03:22:18.177913", "finished": true}, "in": {"text": ["What is the capital of Egypt?"]}, "out": {}}